import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowLeft,ArrowRight,ArrowUpRight,Check} from 'lucide-react';
import {projects,getProject} from '@/lib/projects';
import {site} from '@/lib/site';
import {Eyebrow,ContactCTA} from '@/components/common';
import {ProjectVisual,Screenshot} from '@/components/project-visual';
export function generateStaticParams(){return projects.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=getProject(slug);if(!p)return{title:'Project not found'};return{title:`${p.name} — ${p.category}`,description:p.summary,alternates:{canonical:`/work/${p.slug}`},openGraph:{title:`${p.name} · A project by ${site.name}`,description:p.summary,url:`/work/${p.slug}`}}}
const sections=[['overview','Overview'],['challenge','The challenge'],['contribution','My contribution'],['solution','The solution'],['workflows','Key workflows'],['interface','The interface'],['technical','Technical approach'],['decisions','Engineering decisions'],['outcome','What was delivered']];
export default async function CaseStudy({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const p=getProject(slug);if(!p)notFound();const next=projects[(projects.indexOf(p)+1)%projects.length];
 return <><section className="page-hero case-hero container"><Link href="/work" className="case-back"><ArrowLeft size={14}/> All selected work</Link><Eyebrow>{p.category.toUpperCase()}</Eyebrow><h1>{p.name}</h1><p>{p.headline}</p><div className="case-meta"><div><small>MY ROLE</small><p>{p.role}</p></div><div><small>CONTEXT</small><p>{p.market}</p></div><div><small>DELIVERY</small><p>{p.status}</p></div>{p.url&&<a href={p.url} target="_blank" rel="noopener noreferrer" className="text-link">Visit website <ArrowUpRight size={15}/></a>}</div></section>
 <div className="case-cover container"><ProjectVisual project={p} featured={!!p.image} priority/><p className="image-note">{p.interfaceNote}</p></div>
 <div className="case-body container"><nav className="case-index" aria-label="Case study sections"><span>IN THIS CASE STUDY</span>{sections.map(([id,name],i)=><a href={`#${id}`} key={id}><span>0{i+1}</span>{name}</a>)}</nav><div>
 <section id="overview" className="case-section"><Eyebrow>01 / OVERVIEW</Eyebrow><h2>{p.headline}</h2><p>{p.overview}</p></section>
 <section id="challenge" className="case-section"><Eyebrow>02 / THE CHALLENGE</Eyebrow><h2>Start with the business problem.</h2><p>{p.challenge}</p></section>
 <section id="contribution" className="case-section"><Eyebrow>03 / MY CONTRIBUTION</Eyebrow><h2>Where I focused the work.</h2><ul className="check-list">{p.contribution.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></section>
 <section id="solution" className="case-section"><Eyebrow>04 / PRODUCT & SOLUTION</Eyebrow><h2>A system of connected decisions.</h2><div className="solution-grid">{p.solution.map((s,i)=><article key={s.title}><span>0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section>
 <section id="workflows" className="case-section"><Eyebrow>05 / KEY WORKFLOWS</Eyebrow><h2>{p.kind==='systems'?'Make the work easier to follow.':'A clear journey from the first click.'}</h2><div className="workflow" aria-label="Simplified product workflow">{p.workflow.map((w,i)=><div key={w}><small>0{i+1}{i<p.workflow.length-1&&<ArrowRight size={13}/>}</small>{w}</div>)}</div>{p.slug==='blr-hub'&&<><p>Institutions provide the operational context. Property and tenant records sit alongside inventory, reporting and permission-aware administration.</p><div className="architecture" aria-label="Conceptual module map, not a database isolation diagram"><div>Central administration<small>Institution context · Users · Permissions</small></div><div>Institution operations<small>Inventory · Reporting · Daily workflows</small></div><div>Property operations<small>Buildings · Floors · Rooms · Beds</small></div><div>Tenant lifecycle<small>Assignment · Transfers · Vacancy · History</small></div><div>Administration<small>Route access · Menu actions · Activity</small></div></div><p className="image-note">Conceptual module map based on the supplied scope and inspected source. It does not represent a verified infrastructure or data-isolation diagram.</p></>}</section>
 <section id="interface" className="case-section"><Eyebrow>06 / THE INTERFACE</Eyebrow><h2>{p.image?'Designed to work across screens.':'The operational view.'}</h2><p>{p.interfaceNote}</p>{p.image?<div className="case-gallery"><Screenshot name={p.slug==='bagel-master'?'bagel-menu':p.image} alt={`${p.name} ${p.slug==='bagel-master'?'menu':'desktop'} interface`}/><Screenshot name={p.image} alt={`${p.name} mobile interface`} mobile/></div>:<><div style={{marginTop:24}}><ProjectVisual project={p}/></div><p className="image-note">Simplified presentation only. Demo labels identify fictional records; there are no live customer or financial values.</p></>}</section>
 <section id="technical" className="case-section"><Eyebrow>07 / TECHNICAL APPROACH</Eyebrow><h2>Under the surface.</h2><dl className="tech-table">{p.tech.map(t=><div key={t.label}><dt>{t.label}</dt><dd>{t.value}</dd></div>)}</dl></section>
 <section id="decisions" className="case-section"><Eyebrow>08 / ENGINEERING DECISIONS</Eyebrow><h2>The details that shape the product.</h2>{p.decisions.map(d=><article className="decision" key={d.title}><h3>{d.title}</h3><p>{d.text}</p></article>)}</section>
 <section id="outcome" className="case-section"><Eyebrow>09 / OUTCOME</Eyebrow><h2>What was delivered.</h2><p>{p.outcome}</p><Link className="text-link" style={{marginTop:20}} href={`/contact?project=${encodeURIComponent(p.name)}`}>Discuss a similar project <ArrowUpRight size={16}/></Link></section>
 <div><Eyebrow>10 / KEEP EXPLORING</Eyebrow><Link className="next-project" href={`/work/${next.slug}`}><div><p>NEXT PROJECT · {next.category}</p><h3>{next.name}</h3></div><ArrowUpRight size={26}/></Link></div>
 </div></div><ContactCTA/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'CreativeWork',name:p.name,description:p.summary,url:`${site.url}/work/${p.slug}/`,creator:{'@type':'Person',name:site.fullName}}).replace(/</g,'\\u003c')}}/></>
}
