import type {Metadata} from 'next';
import Link from 'next/link';
import {ArrowDown,ArrowUpRight,Globe2,Check} from 'lucide-react';
import {Eyebrow,Button,ContactCTA,ServicesList,Process,Capabilities} from '@/components/common';
import {ProjectCard} from '@/components/project-card';
import {projects} from '@/lib/projects';
export const metadata:Metadata={alternates:{canonical:'/'}};
export default function Home(){return <>
 <section className="hero container"><div className="hero-top"><Eyebrow>INDEPENDENT PRODUCT ENGINEER & CONSULTANT</Eyebrow><span className="hero-location"><Globe2 size={14}/> Based in India · Working globally</span></div><h1>Software built around<br className="desktop-break"/> how your business<br className="desktop-break"/> <span className="muted">actually works.</span></h1><div className="hero-bottom"><p>I design and build SaaS platforms, internal systems and customer-facing websites. From the way it looks to the way it runs.</p><div className="hero-actions"><Button href="/work">View selected work</Button><Link href="/contact" className="text-link">Discuss a project <ArrowUpRight size={17}/></Link></div></div><div className="trust-strip"><span><Check size={14}/> Delivered for a UK business</span><span><Check size={14}/> Real operational platforms</span><span><Check size={14}/> Design through deployment</span><a href="#selected-work" className="scroll-link">EXPLORE THE WORK <ArrowDown size={14}/></a></div></section>
 <section id="selected-work" className="section work-section container"><div className="section-heading"><div><Eyebrow>SELECTED WORK / 01—06</Eyebrow><h2>Real businesses.<br/><span className="muted">Working software.</span></h2></div><div><p>From a London food business to platforms that manage everyday operations. A selection of the work behind the words.</p><Link href="/work" className="text-link">Explore all selected work <ArrowUpRight size={16}/></Link></div></div><div className="project-grid">{projects.map((p,i)=><ProjectCard key={p.slug} project={p} index={i} featured={i===0}/>)}</div></section>
 <section className="section services-section"><div className="container"><div className="section-heading"><div><Eyebrow>WHAT I CAN HELP WITH</Eyebrow><h2>Built for the work<br/>you need to do.</h2></div><p>A new product, a growing operation or a website that needs to do more. The starting point is your business.</p></div><ServicesList/><Link className="text-link service-more" href="/services">Explore services & product improvements <ArrowUpRight size={16}/></Link></div></section>
 <Process/>
 <section className="about-home container section"><div className="about-mark" aria-hidden="true">Go<span>.</span><small>DESIGN × ENGINEERING</small></div><div><Eyebrow>THE PERSON BEHIND THE WORK</Eyebrow><h2>A product mindset.<br/>An engineer’s follow-through.</h2><p>I’m Gopichand, a full-stack product engineer and software consultant. I work across business platforms, operational systems and customer-facing applications.</p><p>I care about the whole experience: the screen your customer sees, the workflow your team follows and the system that makes it all work.</p><Link className="text-link" href="/about">A little more about how I work <ArrowUpRight size={16}/></Link></div></section>
 <section className="container capability-section"><div className="section-heading"><div><Eyebrow>UNDER THE SURFACE</Eyebrow><h2>The engineering to support it.</h2></div><p>Tools chosen for the product. Capabilities grounded in the work.</p></div><Capabilities/></section><ContactCTA/>
 </>}
