import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Check,Globe2} from 'lucide-react';
import {site} from '@/lib/site';
export function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow"><span/>{children}</p>}
export function Button({href,children,secondary=false}:{href:string;children:React.ReactNode;secondary?:boolean}){return <Link className={`button ${secondary?'button-secondary':''}`} href={href}>{children}<ArrowUpRight size={17}/></Link>}
export function ContactCTA(){return <section className="contact-cta container"><div><Eyebrow>START A CONVERSATION</Eyebrow><h2>What could work<br/><span className="muted">better in your business?</span></h2><p>A platform to build. A workflow to simplify.<br/>A digital experience ready for its next chapter.</p></div><div className="cta-side"><Button href="/contact">Discuss your project</Button><a className="text-link" href={`mailto:${site.email}`}>Or send me an email <ArrowUpRight size={15}/></a><span className="small muted">Based in India. Working Globally.</span></div></section>}
export function Footer(){return <footer className="site-footer"><div className="container footer-top"><Link href="/" className="wordmark" aria-label={`${site.name} home`}>{site.name}<span className="brand-dot">.</span></Link><p>Considered design. Dependable engineering.</p><div><a href={site.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn <ArrowUpRight size={14}/></a><a href={site.github} target="_blank" rel="noopener noreferrer">GitHub <ArrowUpRight size={14}/></a><a href={`mailto:${site.email}`}>Email <ArrowUpRight size={14}/></a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} {site.fullName}</span><span><Globe2 size={13}/> Built for a world that works online.</span><Link href="/privacy">Privacy</Link></div></footer>}
export const services=[
 {title:'Custom business platforms',text:'Bring scattered spreadsheets, repetitive tasks and disconnected processes into one useful system.',items:['Operational systems','Inventory & property management','Business automation']},
 {title:'SaaS & MVP development',text:'Turn a well-defined product idea into a working application, with a clear scope and a foundation for the next stage.',items:['Product scoping','Multi-tenant applications','Launch-ready MVPs']},
 {title:'Dashboards & customer portals',text:'Give your team and customers a clearer way to manage the information and actions that matter.',items:['Admin dashboards','Roles & permissions','Customer self-service']},
 {title:'Premium business websites',text:'A considered digital presence that explains your offer, earns attention and makes the next step obvious.',items:['Brand-led websites','Responsive experiences','Enquiry journeys']},
 {title:'Existing product improvements',text:'Improve the product you already have with clearer workflows, stronger interfaces and practical new features.',items:['Frontend modernisation','Workflow redesign','API integrations']},
];
export function ServicesList({full=false}:{full?:boolean}){return <div className="services-list">{services.slice(0,full?5:4).map((s,i)=><article className="service-row" key={s.title}><span className="row-number">0{i+1}</span><h3>{s.title}</h3><div><p>{s.text}</p>{full&&<ul className="check-list">{s.items.map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul>}</div><Link href={`/contact?type=${encodeURIComponent(s.title)}`} className="circle-link" aria-label={`Discuss ${s.title.toLowerCase()}`}><ArrowUpRight size={22}/></Link></article>)}</div>}
export const processSteps=[['Understand','Start with the business, the people and the problem.'],['Scope','Agree on priorities, deliverables and a practical plan.'],['Design','Map the workflows and make the interface tangible.'],['Build','Develop in clear, reviewable increments.'],['Validate','Check real journeys across devices and roles.'],['Launch','Prepare deployment and handover.'],['Improve','Use feedback to decide what comes next.']];
export function Process(){return <section className="section container"><div className="section-heading"><div><Eyebrow>THE PROCESS</Eyebrow><h2>Clarity at every step.</h2></div><p>You work directly with the person designing and building your product. Clear scope, regular reviews and decisions grounded in your business.</p></div><ol className="process-grid">{processSteps.map(([name,text],i)=><li key={name}><div><span>0{i+1}</span>{i<6&&<ArrowRight size={15}/>}</div><h3>{name}</h3><p>{text}</p></li>)}</ol></section>}
export function Capabilities(){return <div className="capabilities">{[['Interfaces','React','Next.js','TypeScript','Tailwind CSS'],['Application logic','Node.js','Express','REST APIs','WebSockets'],['Data & access','PostgreSQL','MySQL','Authentication','Role-based access'],['Product delivery','Multi-institution systems','Responsive interfaces','Netlify','Vercel']].map(([title,...items])=><div key={title}><h3>{title}</h3>{items.map(x=><span key={x}>{x}</span>)}</div>)}</div>}
