import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Check,Globe2} from 'lucide-react';
import {site} from '@/lib/site';
export function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow"><span/>{children}</p>}
export function Button({href,children,secondary=false}:{href:string;children:React.ReactNode;secondary?:boolean}){return <Link className={`button ${secondary?'button-secondary':''}`} href={href}>{children}<ArrowUpRight size={17}/></Link>}
export function ContactCTA(){return <section className="contact-cta container"><div><Eyebrow>START A CONVERSATION</Eyebrow><h2>What could work<br/><span className="muted">better in your business?</span></h2><p>A platform to build. A workflow to simplify.<br/>A digital experience ready for its next chapter.</p></div><div className="cta-side"><Button href="/contact">Discuss your project</Button><a className="text-link" href={`mailto:${site.email}`}>Or send me an email <ArrowUpRight size={15}/></a><span className="small muted">Based in India. Working Globally.</span></div></section>}
export function Footer(){return <footer className="site-footer"><div className="container footer-top"><Link href="/" className="wordmark" aria-label={`${site.name} home`}>{site.name}<span className="brand-dot">.</span></Link><p>Considered design. Dependable engineering.</p><div><a href={site.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn <ArrowUpRight size={14}/></a><a href={site.github} target="_blank" rel="noopener noreferrer">GitHub <ArrowUpRight size={14}/></a><a href={`mailto:${site.email}`}>Email <ArrowUpRight size={14}/></a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} {site.fullName}</span><span><Globe2 size={13}/> Built for a world that works online.</span><Link href="/privacy">Privacy</Link></div></footer>}
export const services=[
 {title:'Custom business platforms',text:'Connect inventory, sales, procurement and finance with custom ERP systems and enterprise applications built around your operations.',items:['Enterprise resource planning (ERP)','Inventory, orders & billing','Approval workflows & business automation']},
 {title:'Backend engineering & APIs',text:'Build the backend behind your business: structured data, reliable REST APIs and integrations that keep your systems working together.',items:['Node.js & Express services','PostgreSQL & MySQL data modelling','API integrations & background jobs']},
 {title:'Admin & customer management',text:'Manage customers, teams and daily operations through admin dashboards, CRM workflows and customer self-service portals.',items:['Customer relationship management (CRM)','Admin panels & operational reporting','Account management & customer portals']},
 {title:'Real-time systems & integrations',text:'Keep teams in sync with live dashboards, instant notifications and WebSocket updates. Connect external platforms through APIs and webhooks.',items:['Real-time WebSocket communication','Live status updates & notifications','Third-party APIs & webhook integrations']},
 {title:'Application security & access',text:'Address security risks with authenticated access, role-based access control (RBAC), server-side validation and audit trails for sensitive actions.',items:['Authentication & session management','RBAC & server-side permission checks','Input validation, rate limiting & audit logging']},
 {title:'SaaS & MVP development',text:'Turn a product idea into a working SaaS application with multi-tenant architecture, customer onboarding and subscription workflows.',items:['Product scoping & launch-ready MVPs','Multi-tenant applications & tenant isolation','Customer onboarding & subscription integrations']},
 {title:'Premium business websites',text:'A considered digital presence that explains your offer, earns attention and makes the next step obvious.',items:['Brand-led websites','Responsive experiences','Enquiry journeys']},
 {title:'Existing product improvements',text:'Improve the product you already have with clearer workflows, stronger interfaces and practical new features.',items:['Frontend modernisation','Workflow redesign','API integrations']},
];
export function ServicesList({full=false}:{full?:boolean}){return <div className="services-list">{(full?services:services.slice(0,5)).map((s,i)=><article className="service-row" key={s.title}><span className="row-number">0{i+1}</span><h3>{s.title}</h3><div><p>{s.text}</p>{full&&<ul className="check-list">{s.items.map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul>}</div><Link href={`/contact?type=${encodeURIComponent(s.title)}`} className="circle-link" aria-label={`Discuss ${s.title.toLowerCase()}`}><ArrowUpRight size={22}/></Link></article>)}</div>}
export const processSteps=[['Understand','Start with the business, the people and the problem.'],['Scope','Agree on priorities, deliverables and a practical plan.'],['Design','Map the workflows and make the interface tangible.'],['Build','Develop in clear, reviewable increments.'],['Validate','Check real journeys across devices and roles.'],['Launch','Prepare deployment and handover.'],['Improve','Use feedback to decide what comes next.']];
export function Process(){return <section className="section container"><div className="section-heading"><div><Eyebrow>THE PROCESS</Eyebrow><h2>Clarity at every step.</h2></div><p>You work directly with the person designing and building your product. Clear scope, regular reviews and decisions grounded in your business.</p></div><ol className="process-grid">{processSteps.map(([name,text],i)=><li key={name}><div><span>0{i+1}</span>{i<6&&<ArrowRight size={15}/>}</div><h3>{name}</h3><p>{text}</p></li>)}</ol></section>}
export function Capabilities(){return <div className="capabilities">{[['Enterprise applications','ERP & CRM systems','Admin & customer management','Multi-tenant SaaS','React / Next.js / TypeScript'],['Backend & integrations','Node.js & Express','REST APIs & webhooks','Real-time WebSockets','Background job processing'],['Data & security','PostgreSQL & MySQL','Authentication & RBAC','Server-side input validation','Audit logging & rate limiting'],['Product delivery','Workflow automation','Responsive interfaces','Netlify & Vercel','Deployment & handover']].map(([title,...items])=><div key={title}><h3>{title}</h3>{items.map(x=><span key={x}>{x}</span>)}</div>)}</div>}
