import {Building2,LayoutDashboard,Package,Users,ShieldCheck,ChevronDown,ArrowUpRight,Check,BriefcaseBusiness,FileText,CircleDot} from 'lucide-react';
import type {Project} from '@/lib/projects';
export function Screenshot({name,alt,priority=false,mobile=false}:{name:string;alt:string;priority?:boolean;mobile?:boolean}){return <picture>{!mobile&&<source srcSet={`/images/${name}-800.webp 800w, /images/${name}-1440.webp 1440w`} sizes="(max-width: 700px) 92vw, (max-width: 1100px) 80vw, 1100px"/>}<img src={`/images/${name}-${mobile?'mobile':'1440'}.webp`} alt={alt} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':'auto'} width={mobile?390:1440} height={mobile?844:1000}/></picture>}
export function SystemPreview({type}:{type:'blr'|'Payment'}){
 const blr=type==='blr';
 const nav=blr?[[LayoutDashboard,'Overview'],[Building2,'Institutions'],[Package,'Inventory'],[Users,'Tenants'],[ShieldCheck,'Permissions']]:[[LayoutDashboard,'Overview'],[BriefcaseBusiness,'Merchants'],[Users,'Accounts'],[FileText,'Reports'],[ShieldCheck,'Administration']];
 return <div className={`system-preview ${type}`} role="img" aria-label={blr?'Illustrative BLR Hub dashboard with fictional institutions and operational modules':'Illustrative Payment operations interface with fictional merchant workflow records'}>
  <aside className="preview-sidebar"><b className="preview-brand">{blr?'BLR':'Payment'}<span>{blr?'HUB':'.'}</span></b><span className="preview-workspace">{blr?'Operations workspace':'Operations centre'}</span><div className="preview-nav">{nav.map(([Icon,name],i)=>{const I=Icon as typeof Building2;return <div className={i===0?'active':''} key={name as string}><I size={14}/><span>{name as string}</span></div>})}</div><div className="preview-user"><span>DE</span><div>Demo workspace<small>Illustrative data</small></div></div></aside>
  <div className="preview-main"><div className="preview-top"><span>Workspace / Overview</span><span><CircleDot size={12}/> Demo</span></div><div className="preview-title"><div><small>{blr?'YOUR OPERATIONS, CONNECTED':'ADMINISTRATION'}</small><h4>{blr?'Operations overview':'A clearer view of operations'}</h4></div><span className="preview-select">{blr?'All institutions':'All workflows'}<ChevronDown size={12}/></span></div>
  <div className="preview-stat-grid">{(blr?[[Building2,'Institutions','Connected'],[Package,'Inventory','Organised'],[Users,'Tenants','In context']]:[[BriefcaseBusiness,'Merchants','Review & manage'],[ShieldCheck,'Accounts','Structured access'],[FileText,'Reports','Operational view']]).map(([Icon,title,value])=>{const I=Icon as typeof Building2;return <div key={title as string}><I size={17}/><small>{title as string}</small><b>{value as string}</b></div>})}</div>
  <div className="preview-table"><div className="preview-table-head"><b>{blr?'Institution directory':'Merchant workflow'}</b><span>View all <ArrowUpRight size={12}/></span></div><div className="preview-table-labels"><span>{blr?'INSTITUTION':'RECORD'}</span><span>{blr?'MODULE':'TYPE'}</span><span>STATUS</span></div>{(blr?[['Demo · North House','Property & tenants','Active'],['Demo · Central Campus','Institution & inventory','Active'],['Demo · South House','Property & tenants','Active']]:[['Demo · Merchant A','Corporate','In review'],['Demo · Merchant B','Individual','Reviewed'],['Demo · Merchant C','Corporate','In review']]).map(([name,module,status],i)=><div className="preview-table-row" key={name}><span><span className="table-avatar">{blr?<Building2 size={12}/>:<BriefcaseBusiness size={12}/>}</span>{name}</span><span>{module}</span><span className={status==='In review'?'status-review':'status-active'}>{status!=='In review'&&<Check size={10}/>} {status}</span></div>)}</div>
  <div className="preview-bottom"><ShieldCheck size={14}/><span>{blr?'Institution context · Roles · Action permissions':'Account context · Merchant records · Reporting'}</span></div>
 </div></div>
}
export function ProjectVisual({project,featured=false,priority=false}:{project:Project;featured?:boolean;priority?:boolean}){return <div className={`project-visual ${project.theme} ${featured?'featured-visual':''}`}>
 {project.image?<><div className="browser-frame"><div className="browser-bar"><span className="browser-dots"><i/><i/><i/></span><span>{project.url?.replace('https://','').replace(/\/$/,'')}</span><ArrowUpRight size={11}/></div><Screenshot name={project.image} alt={`${project.name} live website, desktop view`} priority={priority}/></div>{featured&&<div className="phone-frame"><Screenshot name={project.image} alt={`${project.name} mobile website`} mobile priority={priority}/></div>}</>:<SystemPreview type={project.slug==='blr-hub'?'blr':'Payment'}/>}
 <span className="visual-caption">{project.image?'LIVE WEBSITE':'ILLUSTRATIVE INTERFACE · SAMPLE DATA'}</span>
 </div>}
